[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=0
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=1
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\vibecoding\ClothSimLab\Installer\ClothSimLab-Setup.exe
FriendlyName=Cloth Simulation
AppLaunched=cmd /c setup.cmd
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles
[Strings]
FILE0="setup.cmd"
FILE1="ClothSimLab-Windows.zip"
[SourceFiles]
SourceFiles0=C:\vibecoding\ClothSimLab\Installer\
[SourceFiles0]
%FILE0%=
%FILE1%=
